- Drop database if exists
DROP TABLE MARVEL;
DROP TABLE DC;
-- CREATE TABLE TO HOLD MARVEL DATA 
CREATE TABLE MARVEL (
name VARCHAR(300),
id VARCHAR(300),
align VARCHAR(300),
eye VARCHAR(300),
hair VARCHAR(300),
sex VARCHAR(300),
alive VARCHAR(300)
);
SELECT *
FROM MARVEL
-- CREATE TABLE TO HOLD DC DATA
CREATE TABLE DC (
name VARCHAR(300),
id VARCHAR(300),
align VARCHAR(300),
eye VARCHAR(300),
hair VARCHAR(300),
sex VARCHAR(300),
alive VARCHAR(300)
);
SELECT *
FROM DC
-- JOIN TABLES 
SELECT *
FROM marvel
UNION ALL
SELECT *
FROM DC;
-- CREATE NEW TABLE
DROP TABLE DcMarvel;

CREATE TABLE DcMarvel AS
(SELECT *
FROM marvel
UNION ALL
SELECT *
FROM DC);

SELECT *
FROM DcMarvel;